### ISSUE TITLE
[Question] 1.11?

### ISSUE THREAD

**Issue by Endgineer** [Silentine/GrimoireOfGaia#42]
I've searched everywhere in the thread, Curseforge, and even Curse but haven't found an answer to this sensitive question; so I thought I'd ask. :3

Are there plans for a 1.11.2 version in the future?

**Comment by Silentine** [comment]
It depends on @DoctorWiggles or when anyone attempts to update it to 1.11.2. The possibility of it being updated to 1.11.2 is out of my hands.

I have had a long issue with updating it myself since 1.6.4. I lack the knowledge to update it between versions. All I can do is add/update features in the mod once the mod is updated.
