### ISSUE TITLE
Incorrect burn time in fuel tooltips

### ISSUE THREAD

**Issue by Lykrast** [Silentine/GrimoireOfGaia#62]
Items that are usable as furnace fuel (like the Coalfish) display burning time in ticks (1/20th of a second) but say that it is seconds.

This means that either:

* Time is correct so tooltips should divide the number by 20, that means for example that Coalfish is intended to burn 0.9 items
* Tooltip is correct so all burn times should be multiplied by 20 (and tooltip divide it by 20), that means that Coalfish is intended to burn 18 items

**Comment by Silentine** [comment]
You are correct. 

The original values were in seconds but got copied over into ticks. The item (Fireshard) is the perfect example as it meant to copy the same values as the Lava Bucket (because they both create lava when right-clicked);

- The Lava Bucket burns for **1000** seconds (20000 ticks)
- The Fireshard burns for 50 seconds (**1000** ticks)

Thanks for bringing this up. I will be fixing it in the next beta release.

**Comment by Silentine** [comment]
Fixed in 1.6.0-beta2.
