### ISSUE TITLE
May we please have a discord?

### ISSUE THREAD

**Issue by Israphelite** [Silentine/GrimoireOfGaia#77]
This would allow the Grimoire of Gaia community to interact much more easily, and even allow the mod creator to interact with the community. Simply putting a link to the discord on the mod page and having it regulated by admins who are trusted friends of the mod creator would be a great idea.

**Comment by Silentine** [comment]
I don't know how to answer this properly as I do not use Discord nor do I know how to.

**Comment by Mrbysco** [comment]
As a Discord user I'd love to help

**Comment by Silentine** [comment]
That's great to hear. I could use help figuring out how Discord works. I have 0 experience with it but I have heard about it a lot.

I think it would be a great way to hear about the ~~complaints~~/suggestions people have for the mod.

My main issue is Timezones. Will messages be saved in the server since the users last login?

**Comment by Mrbysco** [comment]
You'll be able to read back messages. They're stored. It's not IRC :)

**Comment by Silentine** [comment]
Here is a link to the official Discord channel;
https://discord.gg/pGu5afh
Thanks for the suggestion.
