### ISSUE TITLE
Block whitelisting config for better compatibility with Biome mods.

### ISSUE THREAD

**Issue by pirone2** [Silentine/GrimoireOfGaia#81]
## SUGGESTIONS
- [x] I would like to propose new content.
- [ ] I would like to propose changes.
- [ ] I would like to propose another thing.

<!-- SUGGESTIONS INFORMATION - Please explain what you want changed/added and why.
## SUGGESTION INFORMATION
I noticed a bit of an incompatibility with the Biomes o Plenty Mod.
In some of it's added Biomes, the GoG mobs just don't spawn.
After some testing I noticed it's probably because they use special versions of grass and dirt and the such added by the mod, and this probably clashes with the GoG logic of mobs only spawning on specific natural vanilla blocks such as grass sand and snow.

A good fix for this would be the implementation of a config option for the whitelist of blocks the GoG mobs can spawn on. So players or modpack creators could manually add blocks specific to any mods they're using.
If that's not possible just adding the following blocks to the coded whitelist would make GoG more compatible with BoP's biomes:
biomesoplenty:ash_block
biomesoplenty:grass
biomesoplenty:mud
biomesoplenty:flesh
biomesoplenty:dirt
biomesoplenty:white_sand
biomesoplenty:dried_sand
biomesoplenty:hard_ice

The "minecraft:snow_block" also seems to be absent from GoG's whitelist while BoP uses it to fill some biomes

**Comment by pirone2** [comment]
Oops, lost all my text describing the suggestion when it uploaded. Oh well.
Basically while testing with Biomes o Plenty, I noticed some mobs weren't spawning properly.
This is probably because some GoG mobs need specific natural blocks to spawn on.

An option in the config to edit the blocks they can spawn on would be very helpful for modpack creators and players to manually adjust the mobs to spawn on any modded biome.

Alternatively just adding the following blocks to the existing block whitelist would make GoG more compatible with BoP:
biomesoplenty:ash_block
biomesoplenty:grass
biomesoplenty:mud
biomesoplenty:flesh
biomesoplenty:dirt
biomesoplenty:white_sand
biomesoplenty:dried_sand
biomesoplenty:hard_ice
Also the minecraft:snow_block that seems to be absent in the current whitelist.

**Comment by Silentine** [comment]
True, at least for [**day** mobs](http://the-grimoire-of-gaia.wikia.com/wiki/Guide#Spawn_Mechanics).

Thanks for taking your time to list down the blocks in question. But with how the current system is setup, I do not think it is as simple as listing down the blocks without using an API of some sort. 

Even with an API, I don't think I can even run BoP myself. I stopped using that mod around 1.8.9+ because my system could no longer handle it.

If I can figure out a way to include the blocks listed into the whitelist without using an API, sure. But until then, I will leave this suggestion here for future reference.

(I was not aware that minecraft:snow_block spawned naturally. Noted.)

**Comment by Mrbysco** [comment]
Added the config option.

**Comment by Silentine** [comment]
Implemented by **Mrbysco** in (1.6.0).
