### ISSUE TITLE
[Suggestions] Mob's inherent sound

### ISSUE THREAD

**Issue by BlueWither** [Silentine/GrimoireOfGaia#85]
## SUGGESTIONS
- [x] I would like to propose new content.
- [ ] I would like to propose changes.
- [ ] I would like to propose another thing.

-- SUGGESTIONS INFORMATION - Please explain what you want changed/added and why.
## SUGGESTION INFORMATION
At the moment, Mob's voice is shared by neutral mobs and hostile mobs, but how about preparing their own sound files?
<img src="https://i.imgur.com/FNxtxfn.png">

**Comment by Mike-U5** [comment]
So we would be able to customize sounds with sound packs? I would actually like that.

**Comment by Mrbysco** [comment]
There was a person once who offered to make sounds but he was not heard of again.

**Comment by Silentine** [comment]
I think it is a bit too complicated to have separated sound files for each mob. We are talking about roughly 62+ mobs here. Besides, in the past years no one has ever made a sound pack for the current sounds available in the mod.

Currently, mob sound can be customized with sound packs; it is the reason why their sound files have nothing in them. 

I always planned to release a sound pack myself, separate from the mod. Seeing that the last time I made one was for Minecraft 1.5.x, it ain't happening from my end any time soon.

**Comment by Mike-U5** [comment]
> I think it is a bit too complicated to have separated sound files for each mob. We are talking about roughly 62+ mobs here. Besides, in the past years no one has ever made a sound pack for the current sounds available in the mod.  
  
But as far as I have checked, you can only customize the "generic" sounds. It's not possible to add custom sound per mob. (Hence this suggestion, I assume)
So it's not that strange that nobody has made a sound pack.
I had to compile by own branch of the mod to make my custom sounds work. 
(And I gave up on that because the mod is still in Beta and it's too much work in general.)

**Comment by Silentine** [comment]
> But as far as I have checked, you can only customize the "generic" sounds. It's not possible to add custom sound per mob. (Hence this suggestion, I assume)
> So it's not that strange that nobody has made a sound pack.
> I had to compile by own branch of the mod to make my custom sounds work.
> (And I gave up on that because the mod is still in Beta and it's too much work in general.)

Yes, only the generic sounds can be customized (passive, assist and aggressive).

What I meant was that nobody has attempted in the past few years to make a sound pack for those generic sounds alone; I can't expect someone to make a custom sound pack per mob.

Implementing the feature would take a ton of work (at least the way I would do it). I would probably end up making blank sound files for each of those 62+ mobs. Problem is, with the current record in mind, I feel the feature would unlikely be used.

**Comment by Mike-U5** [comment]
I suppose I could make a pull request sometime, assuming you want the sounds added the way they currently are without any fancy stuff added in.

**Comment by Mrbysco** [comment]
Someone else was once gonna compile sounds for us... #19 It never happened

**Comment by Mike-U5** [comment]
I do have a few custom Creative Commons sounds lying around actually, but not sure if you'd like those since I re-used em from one of my old projects.
Here they are: https://soundcloud.com/mr-jane-doe/sets/se-1

**Comment by Silentine** [comment]
> 
> 
> I do have a few custom Creative Commons sounds lying around actually, but not sure if you'd like those since I re-used em from one of my old projects.
> Here they are: https://soundcloud.com/mr-jane-doe/sets/se-1

I am actually laughing; these are pretty good!

I can't imagine adding them to the mod proper though. They would best work as a resource/sound pack.

The main reason why I never added sounds to the mobs proper is because I could never imagine them having sounds. I don't know why but adding _anime_ based sounds kinda makes me cringe. That is why I never updated the sound pack I made.

These sounds though, have a charm to them.

**Comment by Mike-U5** [comment]
Honestly I'd probably hate it if they had anime-esque sounds too.   
(Though I'm somewhat surprised you do too since most mobs resemble anime monster girls :P )
Plus, I'd be hard to tell them apart since they'd all sound similar. And being able to tell mobs apart by sound is one of the main gameplay reasons to have sound.

If you ever do decide to add sounds, then I would base the sounds on the animal-part of the mob rather than the human-part. EG: Ant girls sound likes ants and not girls making ant noises.

**Comment by Mike-U5** [comment]
If I made a pull request and added sounds like this:
https://github.com/Mike-U5/GrimoireOfGaia/blob/master/src/main/java/gaia/init/Sounds.java

And this:  
https://github.com/Mike-U5/GrimoireOfGaia/blob/master/src/main/java/gaia/entity/monster/EntityGaiaVampire.java


Would that be alright? Or would you prefer I'd at the inherit sounds in a different way?
**Note:** This is just so that sound packs can add unique sounds to mobs! I'm **not** adding any actual sound effects.

**Comment by Silentine** [comment]
> 
> 
> If I made a pull request and added sounds like this:
> https://github.com/Mike-U5/GrimoireOfGaia/blob/master/src/main/java/gaia/init/Sounds.java
> 
> And this:
> https://github.com/Mike-U5/GrimoireOfGaia/blob/master/src/main/java/gaia/entity/monster/EntityGaiaVampire.java
> 
> Would that be alright? Or would you prefer I'd at the inherit sounds in a different way?

That seems perfectly fine. Still, does that mean I need to include **null** files for each mob? If I do remember, error messages come up when the sound file is missing.

Also, do note;
> I can't imagine adding them to the mod proper though. They would best work as a resource/sound pack.

Even if you get a system working proper, sounds will still be a separate resource. As much as I hate _anime-esque_ sounds to be added to the mod, I can imagine using your sounds could cause a similar effect to those who use the mod due to the monster girl angle.

I do love the typical Dracula _blah_ sound effect you have (I laughed when I first heard that), but I can imagine players getting into a fit due to it as well.

**Comment by Mike-U5** [comment]
You can override sounds.json with texture packs nowadays.
So I'll put them in the sounds.json like this:

> "vampire_say": { "category": "neutral", "sounds": ["grimoireofgaia:aggressive_say1","grimoireofgaia:aggressive_say2","grimoireofgaia:aggressive_say3"]},
>   "vampire_hurt": { "category": "neutral", "sounds": ["grimoireofgaia:aggressive_hurt1","grimoireofgaia:aggressive_hurt2","grimoireofgaia:aggressive_hurt3"]},
>   "vampire_death": {"category": "neutral", "sounds": ["grimoireofgaia:aggressive_death"]},

Then no extra null sounds should be required.

**Comment by Silentine** [comment]
This had been applied to the next update. When released, I will then close this issue.

**Comment by BlueWither** [comment]
Thank you very much.
