### ISSUE TITLE
Siren doesn't implement setSwingingArms (i.e. func_184724_a), causing a crash

### ISSUE THREAD

**Issue by bbbbbbbbba** [Silentine/GrimoireOfGaia#94]
[crash-2018-10-12_12.38.15-server.txt](https://github.com/Silentine/GrimoireOfGaia/files/2471664/crash-2018-10-12_12.38.15-server.txt)

There are several monsters (e.g. Siren) that implement `GaiaIRangedAttackMob`, but doesn't implement `setSwingingArms`, potentially causing a crash.

The root cause of this issue seems to be that the function `public void setSwingingArms(boolean swingingArms)` in both `EntityMobHostileBase` and `EntityMobPassiveBase` are not properly translated into the appropriate Forge name, `func_184724_a`.

**Comment by Silentine** [comment]
All the ranged mobs do have the `setSwingingArms` (this is the function used by `AbstractSkeleton.java `and other ranged mobs in vanilla Minecraft). 

It is just that they are not properly implemented since I updated the `EntityAIGaiaAttackRangedBow.java` code to match the `EntityAIAttackRangedBow.java` code.

Even if that is the case I have yet to encounter an issue with ranged mobs. If you could describe how I can recreate the crash I will get to fixing this issue as soon as possible.

**Comment by bbbbbbbbba** [comment]
It's as easy as can be. Create a new survival world that allows cheating, and `/summon` a Siren. I get an instant crash.

**Comment by KorDum** [comment]
Forge 14.23.5.2769, me too. With minotaurus same crash.

**Comment by Silentine** [comment]
I'm currently working on a possible solution to this issue. It should be up a in few hours after this post.

**Comment by bbbbbbbbba** [comment]
As far as I know, this crash is fixed in the 1.6.6 release. Closing.

**Comment by KorDum** [comment]
Another crash after update: https://gist.github.com/KorDum/e1c3a331095fd643af09d3e1ff13b5a8

**Comment by Mrbysco** [comment]
KorDom this is not related to this issue. Yes it also says "is abstract" but is not related to isSwinging.

**Comment by Mrbysco** [comment]
Please create a new issue for it.
